### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by mkhan45** [WilliamRagstad/RustScript#5]
Hey, I like the work you've done but I never put an open-source license on RustScript originally since honestly I didn't expect anyone to contribute.

However, for this project to grow it needs to have a license, and I can relicense my changes to the new license. I'd suggest dual-licensing under MIT and Apache 2.0 for the reasons outlined under the "Why?" section of this issue: <https://github.com/bevyengine/bevy/issues/2373>.

**Comment by WilliamRagstad** [comment]
Thanks! Really good suggestion.

Closed by https://github.com/WilliamRagstad/RustScript/commit/c14f19e848ed5fec5bd877ea3f342fdf52d7e228
